name: static check sac
on: pull_request

jobs:
  imports:
    name: Imports
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: golang.org/x/tools/cmd/goimports
      with:
        run: imports
        token: ${{ secrets.GITHUB_TOKEN }}

  errcheck:
    name: Errcheck
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: github.com/kisielk/errcheck
      with:
        run: errcheck
        token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: golang.org/x/lint/golint
      with:
        run: lint
        token: ${{ secrets.GITHUB_TOKEN }}

  shadow:
    name: Shadow
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
      with:
        run: shadow
        token: ${{ secrets.GITHUB_TOKEN }}

  staticcheck:
    name: StaticCheck
    runs-on: windeows-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: honnef.co/go/tools/cmd/staticcheck
      with:
        run: staticcheck
        token: ${{ secrets.GITHUB_TOKEN }}

  sec:
    name: Sec
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: github.com/securego/gosec/cmd/gosec
      with:
        run: sec
        token: ${{ secrets.GITHUB_TOKEN }}
        flags: "-exclude=G104"
