name: static check sac
on: pull_request

jobs:
  imports:
    name: Imports
    runs-on: windows-latest
    steps:
    - uses: ollynth/Modul2_PBP@v1.1.2
    - name: check
      # uses: golang.org/x/tools/cmd/goimports
      uses: k8s-school/golang-github-actions@v1.1.2
      with:
        run: imports
        token: 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
  errcheck:
    name: Errcheck
    runs-on: windows-latest
    steps:
    - uses: ollynth/Modul2_PBP@v1.1.2
    - name: check
      # uses: github.com/kisielk/errcheck
      uses: k8s-school/golang-github-actions@v1.1.2
      with:
        run: errcheck
        token: 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

  lint:
    name: Lint
    runs-on: windows-latest
    steps:
    - uses: ollynth/Modul2_PBP@v1.1.2
    - name: check
      # uses: golang.org/x/lint/golint
      uses: k8s-school/golang-github-actions@v1.1.2
      with:
        run: lint
        token: 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

  shadow:
    name: Shadow
    runs-on: windows-latest
    steps:
    - uses: ollynth/Modul2_PBP@v1.1.2
    - name: check
      # uses: golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
      uses: k8s-school/golang-github-actions@v1.1.2
      with:
        run: shadow
        token: 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

  staticcheck:
    name: StaticCheck
    runs-on: windeows-latest
    steps:
    - uses: ollynth/Modul2_PBP@v1.1.2
    - name: check
      # uses: honnef.co/go/tools/cmd/staticcheck
      uses: k8s-school/golang-github-actions@v1.1.2
      with:
        run: staticcheck
        token: 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

  sec:
    name: Sec
    runs-on: windows-latest
    steps:
    - uses: ollynth/Modul2_PBP@v1.1.2
    - name: check
      # uses: github.com/securego/gosec/cmd/gosec
      uses: k8s-school/golang-github-actions@v1.1.2
      with:
        run: sec
        token: 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
        flags: "-exclude=G104"
